#Dashboard 2
title: "Handy"
views:
  #Seite 1
  - title: Schlafzimmer
    type: custom:grid-layout
    layout:
      grid-template-columns: auto
      grid-template-rows: auto
    cards:
      - type: entity
        entity: sensor.heizung_schlafzimmer_battery_level_3
        name: Heizung Batterie
        unit: "%"
        view_layout:
          grid-column: 1
          grid-row: 1
      - type: thermostat
        entity: climate.heizung_schlafzimmer
        name: Schlafzimmer
        view_layout:
          grid-column: 1
          grid-row: 2
      - type: custom:light-entity-card
        entity: light.schlafzimmer
        name: Schlafzimmer
        persist_features: true
        view_layout:
          grid-column: 1
          grid-row: 3
#Seite 2
  - title: Wohnzimmer
    type: custom:grid-layout
    layout:
      grid-template-columns: auto
      grid-template-rows: auto
    cards:
      - type: entities
        entities:
          - entity: sensor.danfoss_devolo_home_control_radiator_thermostat_battery_level_2
            name: Heizung Bahnhof Batterie
          - entity: sensor.danfoss_devolo_home_control_radiator_thermostat_battery_level
            name: Heizung Balkon Batterie
        view_layout:
          grid-column: 1
          grid-row: 1
      - type: thermostat
        entity: climate.heizung_wohnzimmer_gruppe
        name: Heizung Wohnzimmer
        view_layout:
          grid-column: 1
          grid-row: 2
#Seite 3
  - title: Flur
    type: custom:grid-layout
    layout:
      grid-template-columns: auto
      grid-template-rows: auto
    cards:
      - type: custom:light-entity-card
        entity: light.hall
        name: Flur
        persist_features: true
        view_layout:
          grid-column: 1
          grid-row: 1
#Seite 4
  - title: Küche
    type: custom:grid-layout
    layout:
      grid-template-columns: auto
      grid-template-rows: auto
    cards:
#Seite 5
  - title: Badezimmer
    type: custom:grid-layout
    layout:
      grid-template-columns: auto
      grid-template-rows: auto
    cards:
#Seite 6
  - title: Müll
    type: custom:grid-layout
    layout:
      grid-template-columns: 50% 50%
      grid-template-rows: auto
    cards:
      - type: vertical-stack
        view_layout:
          grid-column: 1
          grid-row: 1 / span 4
        #style: "ha-card { height: 100%; }"
        cards:
          - type: 'custom:button-card'
            #style: "ha-card { height: 100%; }"
            entity: sensor.buttoncardsensor1
            layout: icon_name_state2nd
            show_label: true
            label: |
              [[[
                var days_to = entity.state.split("|")[1]
                if (days_to == 0)
                { return "Heute" }
                else if (days_to == 1)
                { return "Morgen" }
                else
                { return "in " + days_to + " Tagen" }
              ]]]
            show_name: true
            name: |
              [[[
                return entity.state.split("|")[0]
              ]]]
            entity_picture: /local/icon-pictures/restmüll.png
            show_entity_picture: true
            state:
              - color: red
                operator: template
                value: '[[[ return entity.state.split("|")[1] == 0 ]]]'
              - color: orange
                operator: template
                value: '[[[ return entity.state.split("|")[1] == 1 ]]]'
              - value: default
          - type: 'custom:button-card'
            #style: "ha-card { height: 100%; }"
            entity: sensor.buttoncardsensor2
            layout: icon_name_state2nd
            show_label: true
            label: |
              [[[
                var days_to = entity.state.split("|")[1]
                if (days_to == 0)
                { return "Heute" }
                else if (days_to == 1)
                { return "Morgen" }
                else
                { return "in " + days_to + " Tagen" }
              ]]]
            show_name: true
            name: |
              [[[
                return entity.state.split("|")[0]
              ]]]
            entity_picture: /local/icon-pictures/paperwaste_icon.png
            show_entity_picture: true
            state:
              - color: red
                operator: template
                value: '[[[ return entity.state.split("|")[1] == 0 ]]]'
              - color: orange
                operator: template
                value: '[[[ return entity.state.split("|")[1] == 1 ]]]'
              - value: default
          - type: 'custom:button-card'
            #style: "ha-card { height: 100%; }"
            entity: sensor.buttoncardsensor3
            layout: icon_name_state2nd
            show_label: true
            label: |
              [[[
                var days_to = entity.state.split("|")[1]
                if (days_to == 0)
                { return "Heute" }
                else if (days_to == 1)
                { return "Morgen" }
                else
                { return "in " + days_to + " Tagen" }
              ]]]
            show_name: true
            name: |
              [[[
                return entity.state.split("|")[0]
              ]]]
            entity_picture: /local/icon-pictures/Gelber_Sack.png
            show_entity_picture: true
            state:
              - color: red
                operator: template
                value: '[[[ return entity.state.split("|")[1] == 0 ]]]'
              - color: orange
                operator: template
                value: '[[[ return entity.state.split("|")[1] == 1 ]]]'
              - value: default
          - type: 'custom:button-card'
            #style: "ha-card { height: 100%; }"
            entity: sensor.buttoncardsensor4
            layout: icon_name_state2nd
            show_label: true
            label: |
              [[[
                var days_to = entity.state.split("|")[1]
                if (days_to == 0)
                { return "Heute" }
                else if (days_to == 1)
                { return "Morgen" }
                else
                { return "in " + days_to + " Tagen" }
              ]]]
            show_name: true
            name: |
              [[[
                return entity.state.split("|")[0]
              ]]]
            entity_picture: /local/icon-pictures/glas.png
            show_entity_picture: true
            state:
              - color: red
                operator: template
                value: '[[[ return entity.state.split("|")[1] == 0 ]]]'
              - color: orange
                operator: template
                value: '[[[ return entity.state.split("|")[1] == 1 ]]]'
              - value: default
          