title: "  "
views:
  - title: Test
    type: custom:grid-layout
    layout:
      grid-template-columns: 15% 15% 15% 15% 15% auto
      grid-template-rows: auto
      grid-template-areas: |
        "header header header header header sidebar"
        "main main main main main main sidebar"
        "footer footer footer footer footer sidebar"
    cards:
      - type: markdown
        content: >
          ##Schlafzimmer
        view-layout:
          grid-column: 1
          grid-row: 1
      - type: entity
        entity: sensor.heizung_schlafzimmer_battery_level_3
        name: Heizung Batterie
        unit: "%"
        view_layout:
          grid-column: 1
          grid-row: 2
          #grid-area: header


  - title: Test1
    type: custom:xiaomi-vacuum-map-card
    entity: vacuum.robby
    map_camera: camera.xiaomi_cloud_map_extractor
    camera_calibration: true
    language: "de"