title: "  "
views:
  - title: Test
    type: custom:horizontal-layout
    # layout:
    #   grid-template-columns: 50% 50%
    #   grid-template-rows: auto
    #   grid-template-areas: |
    #     "header header header"
    #     "main main . sidebar"
    #     "footer footer footer footer"
    cards:
      - type: thermostat
        entity: climate.heizung_wohnzimmer
        name: Wohnzimmer Bahnhof
        view_layout:
          grid-area:  header
      - type: thermostat
        entity: climate.danfoss_devolo_home_control_radiator_thermostat_heating_1_2
        name: Wohnzimmer Balkon
        view_layout:
          grid-area:  header
      - type: thermostat
        entity: climate.heizung_schlafzimmer
        name: Schlafzimmer
        view_layout:
          grid-area:  header
      - type: button
        view_layout:
          grid-area:  footer
        tap_action:
          action: toggle
        hold_action:
          action: more-info
        icon: mdi:desktop-classic
        show_icon: true
        show_name: true
        entity: switch.windows
        name: Sven-PC
      - type: button
        view_layout:
          grid-area:  footer
        tap_action:
          action: toggle
        hold_action:
          action: more-info
        icon: mdi:home-thermometer-outline
        show_icon: true
        show_name: true
        entity: switch.smart_switch_01_switch
        name: Test