title: "  "
views:
  - title: Test
    type: custom:grid-layout
    layout:
      grid-template-columns: 15% 15% 15% 15% 15% auto
      grid-template-rows: auto
      grid-template-areas: |
        "header header header header header sidebar"
        "main main main main main main sidebar"
        "footer footer footer footer footer sidebar"
    cards:
#Beschreibung der Spalten
      - type: markdown
        content: >
          # Schlafzimmer
        view-layout:
          grid-column: 1
          grid-row: 1
      - type: markdown
        content: >
          # Wohnzimmer
        view-layout:
          grid-column: 2
          grid-row: 1
      - type: markdown
        content: >
          # Flur
        view-layout:
          grid-column: 3
          grid-row: 1
      - type: markdown
        content: >
          # Küche
        view-layout:
          grid-column: 4
          grid-row: 1
      - type: markdown
        content: >
          # Badezimmer
        view-layout:
          grid-column: 5
          grid-row: 1
      - type: markdown
        content: >
          # Müll
        view-layout:
          grid-column: 6
          grid-row: 1
#Inhalt der Spalten
      - type: entity
        entity: sensor.heizung_schlafzimmer_battery_level_3
        name: Heizung Batterie
        unit: "%"
        view_layout:
          grid-column: 1
          grid-row: 2
      - type: entities
        entities:
          - entity: sensor.danfoss_devolo_home_control_radiator_thermostat_battery_level_2
            name: Heizung Bahnhof Batterie
          - entity: sensor.danfoss_devolo_home_control_radiator_thermostat_battery_level
            name: Heizung Balkon Batterie
        view_layout:
          grid-column: 2
          grid-row: 2
      #- type: entity
      #  entity: sensor.heizung_schlafzimmer_battery_level_3
      #  name: Heizung Batterie
      #  unit: "%"
      #  view_layout:
      #    grid-column: 1
      #    grid-row: 2


  - title: Test1
    type: custom:xiaomi-vacuum-map-card
    entity: vacuum.robby
    map_camera: camera.xiaomi_cloud_map_extractor
    camera_calibration: true
    language: "de"