title: "  "
views:
  - title: Test1
    type: custom:xiaomi-vacuum-map-card
    entity: vacuum.robby
    map_camera: camera.xiaomi_cloud_map_extractor
    camera_calibration: true
    language: "de"
    modes: 
      - go_to_target
  - title: Test
    type: custom:grid-layout
    layout:
      grid-template-columns: 1fr 1fr 1fr
      grid-template-rows: auto 250px 250px 250px auto
      grid-template-areas: |
        ". . ."
        "p11 p12 p13"
        "p21 p21 p23"
        "p31 p31 p31"
    cards:
      - type: thermostat
        entity: climate.heizung_wohnzimmer
        name: Wohnzimmer Bahnhof
        view_layout:
          grid-area: p11
      - type: thermostat
        entity: climate.danfoss_devolo_home_control_radiator_thermostat_heating_1_2
        name: Wohnzimmer Balkon
        view_layout:
          grid-area: p12
      - type: thermostat
        entity: climate.heizung_schlafzimmer
        name: Schlafzimmer
        view_layout:
          grid-area: p13
      - type: custom:button-card
        styles:
          icon:
            - height:  60px
            - width: 60px
        view_layout:
          grid-area: p21
        tap_action:
          action: toggle
        hold_action:
          action: more-info
        entity: switch.scenes
      - type: custom:button-card
        styles:
          icon:
            - height:  60px
            - width: 60px
        view_layout:
          grid-area: p23
        tap_action:
          action: toggle
        hold_action:
          action: more-info
        entity: switch.scenes_schlafzimmer
      - type: history-graph
        entities:
          - climate.danfoss_devolo_home_control_radiator_thermostat_heating_1_2
          - climate.heizung_schlafzimmer
          - climate.heizung_wohnzimmer
        hours_to_show: 80
        title: Temperatur 1. Stock
        view_layout:
          grid-area: p31