title: "  "
views:
  - title: Test
    type: custom:grid-layout
    layout:
      grid-template-columns: 15% 15% 15% 15% 15% 25%
      grid-template-rows: auto
    cards:
#Beschreibung der Spalten
      - type: markdown
        content: >
          # Schlafzimmer
        view-layout:
          grid-column: 1
          grid-row: 1
      - type: markdown
        content: >
          # Wohnzimmer
        view-layout:
          grid-column: 2
          grid-row: 1
      - type: markdown
        content: >
          # Flur
        view-layout:
          grid-column: 3
          grid-row: 1
      - type: markdown
        content: >
          # K端che
        view-layout:
          grid-column: 4
          grid-row: 1
      - type: markdown
        content: >
          # Badezimmer
        view-layout:
          grid-column: 5
          grid-row: 1
      - type: markdown
        content: >
          # M端ll
        view-layout:
          grid-column: 6
          grid-row: 1
#Inhalt der Spalten
      - type: entity
        entity: sensor.heizung_schlafzimmer_battery_level_3
        name: Heizung Batterie
        unit: "%"
        view_layout:
          grid-column: 1
          grid-row: 2
      - type: entities
        entities:
          - entity: sensor.danfoss_devolo_home_control_radiator_thermostat_battery_level_2
            name: Heizung Bahnhof Batterie
          - entity: sensor.danfoss_devolo_home_control_radiator_thermostat_battery_level
            name: Heizung Balkon Batterie
        view_layout:
          grid-column: 2
          grid-row: 2
      - type: thermostat
        entity: climate.heizung_schlafzimmer
        name: Schlafzimmer
        view_layout:
          grid-column: 1
          grid-row: 3
      - type: thermostat
        entity: climate.heizung_wohnzimmer_gruppe
        name: Heizung Wohnzimmer
        view_layout:
          grid-column: 2
          grid-row: 3
      - type: custom:light-entity-card
        entity: light.hall
        name: Flur
        persist_features: true
        view_layout:
          grid-column: 3
          grid-row: 4
      - type: custom:light-entity-card
        entity: light.schlafzimmer
        name: Schlafzimmer
        persist_features: true
        view_layout:
          grid-column: 1
          grid-row: 4
#M端ll
      - type: horizontal-stack
        #gridrow: 1 / 2
        gridcol: 6
        style: "ha-card { height: 100%; }"
        cards:
          - type: 'custom:button-card'
            style: "ha-card { height: 100%; }"
            entity: sensor.buttoncardsensor1
            layout: icon_name_state2nd
            show_label: true
            label: |
              [[[
                var days_to = entity.state.split("|")[1]
                if (days_to == 0)
                { return "Heute" }
                else if (days_to == 1)
                { return "Morgen" }
                else
                { return "in " + days_to + " Tagen" }
              ]]]
            show_name: true
            name: |
              [[[
                return entity.state.split("|")[0]
              ]]]
            entity_picture: /local/icon-pictures/restm端ll.png
            show_entity_picture: true
            state:
              - color: red
                operator: template
                value: '[[[ return entity.state.split("|")[1] == 0 ]]]'
              - color: orange
                operator: template
                value: '[[[ return entity.state.split("|")[1] == 1 ]]]'
              - value: default
          - type: 'custom:button-card'
            style: "ha-card { height: 100%; }"
            entity: sensor.buttoncardsensor2
            layout: icon_name_state2nd
            show_label: true
            label: |
              [[[
                var days_to = entity.state.split("|")[1]
                if (days_to == 0)
                { return "Heute" }
                else if (days_to == 1)
                { return "Morgen" }
                else
                { return "in " + days_to + " Tagen" }
              ]]]
            show_name: true
            name: |
              [[[
                return entity.state.split("|")[0]
              ]]]
            entity_picture: /local/icon-pictures/paperwaste_icon.png
            show_entity_picture: true
            state:
              - color: red
                operator: template
                value: '[[[ return entity.state.split("|")[1] == 0 ]]]'
              - color: orange
                operator: template
                value: '[[[ return entity.state.split("|")[1] == 1 ]]]'
              - value: default
      - type: horizontal-stack
        #gridrow: 2 / 3
        gridcol: 6
        style: "ha-card { height: 100%; }"
        cards:
          - type: 'custom:button-card'
            style: "ha-card { height: 100%; }"
            entity: sensor.buttoncardsensor3
            layout: icon_name_state2nd
            show_label: true
            label: |
              [[[
                var days_to = entity.state.split("|")[1]
                if (days_to == 0)
                { return "Heute" }
                else if (days_to == 1)
                { return "Morgen" }
                else
                { return "in " + days_to + " Tagen" }
              ]]]
            show_name: true
            name: |
              [[[
                return entity.state.split("|")[0]
              ]]]
            entity_picture: /local/icon-pictures/Gelber_Sack.png
            show_entity_picture: true
            state:
              - color: red
                operator: template
                value: '[[[ return entity.state.split("|")[1] == 0 ]]]'
              - color: orange
                operator: template
                value: '[[[ return entity.state.split("|")[1] == 1 ]]]'
              - value: default
          - type: 'custom:button-card'
            style: "ha-card { height: 100%; }"
            entity: sensor.buttoncardsensor4
            layout: icon_name_state2nd
            show_label: true
            label: |
              [[[
                var days_to = entity.state.split("|")[1]
                if (days_to == 0)
                { return "Heute" }
                else if (days_to == 1)
                { return "Morgen" }
                else
                { return "in " + days_to + " Tagen" }
              ]]]
            show_name: true
            name: |
              [[[
                return entity.state.split("|")[0]
              ]]]
            entity_picture: /local/icon-pictures/glas.png
            show_entity_picture: true
            state:
              - color: red
                operator: template
                value: '[[[ return entity.state.split("|")[1] == 0 ]]]'
              - color: orange
                operator: template
                value: '[[[ return entity.state.split("|")[1] == 1 ]]]'
              - value: default



  - title: Test1
    type: custom:xiaomi-vacuum-map-card
    entity: vacuum.robby
    map_camera: camera.xiaomi_cloud_map_extractor
    camera_calibration: true
    language: "de"